<a href="https://colab.research.google.com/github/javed163/Pytorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [11]:
df.shape

(569, 33)

In [12]:
df = df.drop(columns = ['id','Unnamed: 32'])

In [13]:
df.head(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                   0.1189  

[1 rows x 31 columns]

In [14]:
# train test split

x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size = 0.2)


In [15]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
x_train

array([[-0.03827087, -0.76377631, -0.10177618, ..., -0.62008215,
        -0.29188751, -0.65556239],
       [-0.33173837, -1.17639938, -0.33367907, ..., -0.86288917,
        -0.74315193,  0.90905474],
       [ 0.58499822,  0.3514849 ,  0.59474621, ...,  0.64878522,
         0.29028981, -0.12635366],
       ...,
       [-0.51340873,  0.70751966, -0.50577543, ..., -0.5078426 ,
        -0.9957368 ,  0.35683693],
       [-0.7929016 , -0.14366279, -0.79423009, ..., -0.45513091,
         0.22406329, -0.90263604],
       [-0.3932268 ,  0.51653412, -0.41748959, ..., -1.02602277,
        -1.1328103 , -0.85442654]])

In [17]:
x_test

array([[ 1.04336652,  0.42457812,  1.30672878, ...,  1.22588737,
         0.50899134,  1.94446313],
       [-0.19478687,  0.3774212 , -0.15792109, ...,  1.67121028,
        -0.16559507,  1.24871252],
       [-0.39602173, -0.08943233, -0.4235923 , ..., -0.48996909,
        -0.26262463, -0.65337105],
       ...,
       [-0.53297324,  2.53485038, -0.6046393 , ..., -1.74899089,
        -0.77857542, -0.92454944],
       [ 0.20768285, -1.01135015,  0.1695909 , ..., -0.01162563,
        -0.34887312, -0.08636169],
       [ 1.15516366,  0.3208329 ,  1.16026379, ...,  0.53821184,
         0.24562541, -0.3109741 ]])

In [18]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

In [19]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,

In [20]:
y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1])

# Numpy array to pytorch tensors

In [21]:
import torch
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [22]:
y_train_tensor.shape

torch.Size([455])

In [23]:
y_test_tensor.shape

torch.Size([114])

In [24]:
x_train_tensor.shape

torch.Size([455, 30])

In [25]:
x_train_tensor.shape

torch.Size([455, 30])

# defining the model





In [37]:
class MysimpleNN:

  def __init__(self,x):
    self.weight = torch.rand(x.shape[1], 1 , dtype=torch.float64, requires_grad = True)
    self.bias = torch.rand(1, dtype = torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weight) +self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_calculate(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


# important parameters

In [33]:
learning_rates = 0.01
epochs = 4

# Trainig pipeline

In [34]:
# define the model

model = MysimpleNN(x_train_tensor)
model.weight

tensor([[0.4624],
        [0.8349],
        [0.8929],
        [0.3303],
        [0.7124],
        [0.1177],
        [0.3215],
        [0.0369],
        [0.8831],
        [0.6694],
        [0.3382],
        [0.3665],
        [0.2304],
        [0.5901],
        [0.4390],
        [0.6686],
        [0.8443],
        [0.2607],
        [0.1876],
        [0.6145],
        [0.4739],
        [0.9705],
        [0.1527],
        [0.3816],
        [0.3294],
        [0.9500],
        [0.7663],
        [0.4611],
        [0.9785],
        [0.0389]], dtype=torch.float64, requires_grad=True)

In [35]:
model.bias

tensor([0.2461], dtype=torch.float64, requires_grad=True)

In [41]:
# define the model

model = MysimpleNN(x_train_tensor)

# define the loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(x_train_tensor)

  # calculate loss function
  loss = model.loss_calculate(y_pred, y_train_tensor)


  # calculate gradients
  loss.backward()  # This line is added

  # parameters updates
  with torch.no_grad():
    model.weight -= learning_rates * model.weight.grad
    model.bias -= learning_rates * model.bias.grad

    # grad to zeros
    model.weight.grad.zero_()
    model.bias.grad.zero_()

    #print each loss in epoch
    print(f'epoch: {epoch+1}, loss:{loss.item()}')

epoch: 1, loss:4.055953392525551
epoch: 2, loss:4.0449603339557445
epoch: 3, loss:4.033977984319481
epoch: 4, loss:4.023006441289354


In [43]:
model.bias

tensor([0.8912], dtype=torch.float64, requires_grad=True)

# Evaluation

In [47]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'accuracy: {accuracy.item()}')



accuracy: 0.5235456824302673
